# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yuri
keywords: yuri,博客,日记,前端,极客,jekyll
email: 461299370@qq.com
description: > # this means to ignore newlines until "baseurl:"
  yuri博客专注于记录自己的一些日志，以及一些前端包括html、css、js的相关技术文章。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yygmf.top" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Yuri
github_username:  Yuri
safe: false
highlighter: rouge
encoding: utf-8

timezone: Asia/Shanghai
paginate: 10
paginate_path: "/page:num"
# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock


tag_page_layout: tag_page
tag_page_dir: tag

kramdown:
  # auto_ids:       true
  # entity_output:  as_char
  # toc_levels:     1..6
  # smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: true
  # footnote_nr:    1
  syntax_highlighter: rouge
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter_opts:
    # disable: false
    css_class: 'highlight'
    default_lang: markdown
    # line_numbers: true


sass:
  style: compressed

contentsLabel: 文章目录